name: Use Tekton Dir

on:
  workflow_dispatch:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0

      - run: export KUBECONFIG="$(kind get kubeconfig-path)"

      - run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

      - uses: jerop/tkn@v0.1.0

      - run: tkn task create -f tekton/task.yaml

      - run: tkn task describe greet

      - run: |
          tkn task start greet --showlog \
            -p name=Seafarer \