name: Use Catalog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0

      - run: export KUBECONFIG="$(kind get kubeconfig-path)"

      - run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

      - uses: jerop/tkn@v0.1.0

      - run: tkn hub install task git-clone
      - run: tkn task describe git-clone
      - run: |
          tkn task start git-clone --showlog \
            -p url=https://github.com/jerop/test-tkn \
            -w name=output,volumeClaimTemplateFile=tekton/workspace.yaml
      
      - run: tkn hub install task golang-test
      - run: tkn task describe golang-test
      - run: |
          tkn task start golang-test --showlog \
            -p package=github.com/jerop/test-tkn \
            -w name=source,claimName=pvc    
      
      
